services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4a.command.getSpielplan:
        class: Janborg\H4aTabellen\Command\H4aSpielplanCommand
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'
    
    h4a.command.updateResults:
        class: Janborg\H4aTabellen\Command\H4aUpdateResultsCommand
        arguments:
            - '@contao.framework'
        tags: 
            - "console.command"

    h4a.command.updateReports:
        class: Janborg\H4aTabellen\Command\H4aUpdateReportsCommand
        arguments:
            - '@contao.framework'
        tags: 
            - "console.command"