services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4a.command.getSpielplan:
        class: Janborg\H4aTabellen\Command\H4aSpielplanCommand
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'