services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    Janborg\H4aTabellen\Migration\H4aSeasonsMigration:
        arguments:
            - '@database_connection'
            - '@contao.framework'