services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - ['setContainer', ['@Psr\Container\ContainerInterface']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    Janborg\H4aTabellen\Controller\ContentElement\H4aSpielplanElement: ~

    Janborg\H4aTabellen\Controller\ContentElement\H4aLigaSpielplanElement: ~

    Janborg\H4aTabellen\Controller\ContentElement\H4aTabelleElement: ~

    Janborg\H4aTabellen\Controller\ContentElement\H4aAktuelleSpieleElement: ~

    Janborg\H4aTabellen\Cron\H4aCron:
        arguments:
            - '@contao.framework'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateResults
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateReports
            -
                name: contao.cronjob
                interval: "hourly"
                method: updateEvents

    Janborg\H4aTabellen\Migration\H4aSeasonsMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
        