services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4a.command.getSpielplan:
        class: Janborg\H4aTabellen\Command\H4aSpielplanCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.h4aapihelper'
    
    h4a.command.updateResults:
        class: Janborg\H4aTabellen\Command\H4aUpdateResultsCommand
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@h4atabellen.h4aapihelper'

    h4a.command.updateReports:
        class: Janborg\H4aTabellen\Command\H4aUpdateReportsCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.h4aapihelper'

    h4a.command.updateEvents:
        class: Janborg\H4aTabellen\Command\H4aUpdateEventsCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.h4aeventautomator'

    h4a.command.showteams:
        class: Janborg\H4aTabellen\Command\ShowTeamsCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.crawler.teamscrawler'
        tags: 
            - "console.command"

    h4a.command.showverbaende:
        class: Janborg\H4aTabellen\Command\ShowVerbaendeCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.crawler.verbandscrawler'
        tags: 
            - "console.command"