services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4a.command.updateResults:
        class: Janborg\H4aTabellen\Command\H4aUpdateResultsCommand
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@h4atabellen.handballnet.apiclient'
            - '@event_dispatcher'

    h4a.command.updateEvents:
        class: Janborg\H4aTabellen\Command\H4aUpdateEventsCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.handballnet.eventautomator'

    h4a.command.showgamesdata:
        class: Janborg\H4aTabellen\Command\ShowGamesDataCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.handballnet.apiclient'
        tags: 
            - "console.command"

    h4a.command.showclubteams:
        class: Janborg\H4aTabellen\Command\ShowClubTeamsCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.handballnet.apiclient'
        tags: 
            - "console.command"

    h4a.command.showteamschedule:
        class: Janborg\H4aTabellen\Command\ShowTeamScheduleCommand
        arguments:
            - '@contao.framework'
            - '@h4atabellen.handballnet.apiclient'
        tags: 
            - "console.command"