services:
    _defaults:
        autoconfigure: true

    Janborg\H4aTabellen\Controller\ContentElement\H4aSpielplanElement: 
        public: true
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.h4aapihelper'

    Janborg\H4aTabellen\Controller\ContentElement\H4aLigaSpielplanElement: 
        public: true    
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.h4aapihelper'

    Janborg\H4aTabellen\Controller\ContentElement\H4aTabelleElement: 
        public: true
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.h4aapihelper'

    Janborg\H4aTabellen\Controller\ContentElement\H4aAktuelleSpieleElement: 
        public: true
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.h4aapihelper'

    Janborg\H4aTabellen\Backend\UpdateH4aResultsController:
        public: true
        arguments:
            - '@contao.cache.entity_tags'
            - '@h4atabellen.h4aapihelper'

    Janborg\H4aTabellen\Backend\UpdateH4aEventsController:
        public: true
        arguments:
            - '@h4atabellen.h4aeventautomator'

    Janborg\H4aTabellen\Backend\UpdateH4aCalendarsController:
        public: true
        arguments:
            - '@h4atabellen.h4aeventautomator'

    Janborg\H4aTabellen\Backend\UpdateHandballnetTeamsController:
        public: true
        arguments:
            - '@h4atabellen.crawler.teamscrawler'