services:
    _defaults:
        autoconfigure: true

    Janborg\H4aTabellen\Controller\ContentElement\H4aSpielplanElement: 
        public: true
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.h4aapihelper'

    Janborg\H4aTabellen\Controller\ContentElement\H4aTabelleElement: 
        public: true
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.h4aapihelper'

    Janborg\H4aTabellen\Controller\ContentElement\HandballnetSpielplanElement: 
        public: true
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.handballnet.apiclient'
            - '@?monolog.logger.contao.general'
            - '%janborg_h4a_tabellen.handballnet_cache_ttl%'

    Janborg\H4aTabellen\Controller\ContentElement\HandballnetTabelleElement: 
        public: true
        arguments:
            - '@contao.routing.scope_matcher'
            - '@h4atabellen.handballnet.apiclient'
            - '@?monolog.logger.contao.general'
            - '%janborg_h4a_tabellen.handballnet_cache_ttl%'

    Janborg\H4aTabellen\Backend\UpdateH4aResultsController:
        public: true
        arguments:
            - '@contao.cache.tag_manager'
            - '@h4atabellen.handballnet.apiclient'
            - '@event_dispatcher'
            - '@router'

    Janborg\H4aTabellen\Backend\UpdateH4aEventsController:
        public: true
        arguments:
            - '@h4atabellen.h4aeventautomator'
            - '@router'

    Janborg\H4aTabellen\Backend\UpdateH4aCalendarsController:
        public: true
        arguments:
            - '@h4atabellen.h4aeventautomator'
            - '@router'

    Janborg\H4aTabellen\Backend\UpdateHandballnetTeamsController:
        public: true
        arguments:
            - '@h4atabellen.handballnet.apiclient'
            - '@router'