services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    h4atabellen.calendarevents.onload.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\CalendarEventsExtendPaletteCallback   
        arguments:
            - '@request_stack'

    h4atabellen.calendarevents.list.childrecords.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\CalendarEventsListChildRecordsCallback   
        arguments:
            - '@request_stack'

    h4atabellen.calendar.cheackseasondata.onload.callback: 
        class: Janborg\H4aTabellen\EventListener\DataContainer\CalendarCheckSeasonDataCallback
        arguments:
            - '@request_stack'

    h4atabellen.calendar.handballnetteamid.options.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\HandballnetTeamIdOptionsCallback   
        arguments:
            - '@request_stack'

    h4atabellen.calendar.handballnettournamentid.options.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\HandballnetTournamentIdOptionsCallback   
        arguments:
            - '@request_stack'

    h4atabellen.clubs.check_handballnet_id.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\HandballnetCheckClubIdCallback
        arguments:
            - '@h4atabellen.handballnet.apiclient'
            - '@request_stack'
    
    h4atabellen.clubs.fill_handballnet_data.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\HandballnetFillClubDataCallback
        arguments:
            - '@h4atabellen.handballnet.apiclient'
            - '@request_stack'
    