services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    h4atabellen.calendarevents.onload.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\CalendarEventsExtendPaletteCallback   
        arguments:
            - '@request_stack'

    h4atabellen.calendarevents.list.childrecords.callback:
        class: Janborg\H4aTabellen\EventListener\DataContainer\CalendarEventsListChildRecordsCallback   
        arguments:
            - '@request_stack'