services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    janborg.h4atabellen.migration.h4aseasons:
        class: Janborg\H4aTabellen\Migration\H4aSeasonsMigration
        arguments:
            - "@database_connection"
            - "@contao.framework"

    janborg.h4atabellen.migration.mcvtocgw:
        class: Janborg\H4aTabellen\Migration\MultiColumnWizardToContaoGroupWidgetWMigration
        arguments:
            - "@database_connection"
