services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    # Registriere die Migration für das Bundle
    Janborg\H4aTabellen\Migration\Version500\CreateHandballnetClubsFromH4aSeasonsMigration:
        public: true
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $handballnetApiClient: '@h4atabellen.handballnet.apiclient' 
            $seasonSync: '@h4atabellen.handballnet.seasonsync'
            $teamSync: '@h4atabellen.handballnet.teamsync'

    Janborg\H4aTabellen\Migration\Version500\LinkHandballnetTeamsToCalendarsMigration:
        public: true
        arguments:
            $connection: '@doctrine.dbal.default_connection'
        
    Janborg\H4aTabellen\Migration\Version500\LinkHandballnetClubToTabelleElementsMigration:
        public: true
        arguments:
            $connection: '@doctrine.dbal.default_connection'
        
    Janborg\H4aTabellen\Migration\Version500\LinkHandballnetClubToSpielplanElementsMigration:
        public: true
        arguments:
            $connection: '@doctrine.dbal.default_connection'
        
    Janborg\H4aTabellen\Migration\Version500\MigrateCalendarEventsToHandballnetSchemaMigration:
        public: true
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $handballnetEventAutomator: '@h4atabellen.handballnet.eventautomator'
        