services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    # Registriere die Migration für das Bundle
    Janborg\H4aTabellen\Migration\CreateHandballnetClubsFromH4aSeasonsMigration:
        public: true
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $handballnetApiClient: '@h4atabellen.handballnet.apiclient' 
            $seasonSync: '@h4atabellen.handballnet.seasonsync'
            $teamSync: '@h4atabellen.handballnet.teamsync'
