services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4atabellen.h4aeventautomator:
        class: Janborg\H4aTabellen\H4aEventAutomator\H4aEventAutomator
        public: true
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'

    h4atabellen.cron.updateresults:
        class: Janborg\H4aTabellen\Cron\UpdateH4aResultsCron
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@monolog.logger.contao.cron'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateResults
                priority: 50
    
    h4atabellen.cron.updateevents:
        class: Janborg\H4aTabellen\Cron\UpdateH4aEventsCron
        arguments:
            - '@contao.framework'
            - '@h4atabellen.h4aeventautomator'
            - '@monolog.logger.contao.cron'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateEvents
                priority: 10

    h4atabellen.cron.updatereportno:
        class: Janborg\H4aTabellen\Cron\UpdateH4aReportNoCron
        arguments:
            - '@contao.framework'
            - '@monolog.logger.contao.cron'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateReportNo
                priority: 40