services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4atabellen.h4aeventautomator:
        class: Janborg\H4aTabellen\H4aEventAutomator\H4aEventAutomator
        public: true
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@h4atabellen.handballnet.apiclient'
            - '@?monolog.logger.contao.general'
    
    h4atabellen.cron.updateresults:
        class: Janborg\H4aTabellen\Cron\UpdateH4aResultsCron
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@?monolog.logger.contao.cron'
            - '@h4atabellen.handballnet.apiclient'
            - '@event_dispatcher'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateResults
                priority: 50
    
    h4atabellen.cron.updateevents:
        class: Janborg\H4aTabellen\Cron\UpdateH4aEventsCron
        arguments:
            - '@contao.framework'
            - '@h4atabellen.h4aeventautomator'
            - '@?monolog.logger.contao.cron'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateEvents
                priority: 10

    h4atabellen.cron.updatehandballnetseasons:
        class: Janborg\H4aTabellen\Cron\UpdateHandballnetSeasonsCron
        arguments:
            - '@contao.framework'
            - '@h4atabellen.handballnet.apiclient'
            - '@?monolog.logger.contao.cron'
        tags:
            -
                name: contao.cronjob
                interval: 'daily'
                method: updateHandballnetSeasons
                priority: 20

    h4atabellen.cron.updatehandballnetteams:
        class: Janborg\H4aTabellen\Cron\UpdateHandballnetTeamsCron
        arguments:
            - '@contao.framework'
            - '@h4atabellen.handballnet.apiclient'
            - '@event_dispatcher'
            - '@h4atabellen.handballnet.handballnetteamsparser'
            - '@?monolog.logger.contao.cron'
        tags:
            -
                name: contao.cronjob
                interval: 'daily'
                method: updateHandballnetTeams
                priority: 10

    h4atabellen.crawler.reportnocrawler:
        class: Janborg\H4aTabellen\Crawler\H4aReportNoCrawler
        public: true

    h4atabellen.handballnet.apiclient:
        class: Janborg\H4aTabellen\HandballnetApiClient
        public: true
        arguments:
            - '@cache.app'
            - '@http_client'
            - '@?monolog.logger.contao.general'
            - 'https://www.handball.net/a/sportdata/1/'
            - '%janborg_h4a_tabellen.handballnet_cache_ttl%'

    h4atabellen.handballnet.handballnetteamsparser:
        class: Janborg\H4aTabellen\HandballNet\Parser\HandballnetTeamsParser
        public: true

    h4atabellen.handballnet.seasonsync:
        class: Janborg\H4aTabellen\Sync\HandballnetSeasonSync
        public: true
        arguments:
            $handballnetApiClient: '@h4atabellen.handballnet.apiclient' 

    h4atabellen.handballnet.teamsync:
        class: Janborg\H4aTabellen\Sync\HandballnetTeamSync
        public: true
        arguments:
            $handballnetApiClient: '@h4atabellen.handballnet.apiclient' 
            $teamsParser: '@h4atabellen.handballnet.handballnetteamsparser'