services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    Janborg\H4aTabellen\H4aEventAutomator\H4aEventAutomator:
        arguments:
            - '@contao.cache.entity_tags'

    h4atabellen.cron.updates:
        class: Janborg\H4aTabellen\Cron\H4aCron
        arguments:
            - '@contao.framework'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateResults
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateReports
            -
                name: contao.cronjob
                interval: "hourly"
                method: updateEvents
