version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    default_assignees:
      - "janborg"
    default_labels:
      - "dependabot"
    commit_message:
      prefix: "chore"
      include_scope: true