name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
      - '5.x'
      - '4.x'

jobs:
  ecs:
    name: ECS (PHP 8.4)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, sqlite, zlib
          coverage: none
      - run: composer install --no-interaction --no-suggest --no-scripts
      - name: Check coding style
        run: vendor/bin/ecs check src tests --config ecs.php --ansi --no-progress-bar

  phpstan:
    name: PHPStan (PHP 8.4)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, sqlite, zlib
          coverage: none
      - run: composer install --no-interaction --no-suggest --no-scripts
      - name: Analyze code
        run: vendor/bin/phpstan analyse src tests --configuration phpstan.neon --no-progress --ansi

  depcheck:
    name: Dependency Analyser (PHP 8.4)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, sqlite, zlib
          coverage: none
      - run: composer install --no-interaction --no-suggest --no-scripts
      - name: Check dependencies
        run: vendor/bin/composer-dependency-analyser --config=composer-dependency-analyser.php

  tests:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, sqlite, zlib
          coverage: none
      - run: composer install --no-interaction --no-suggest --no-scripts
      - name: Run unit tests
        run: vendor/bin/phpunit --colors=always